# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171119_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='returned_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.SaleItem'),
            preserve_default=False,
        ),
    ]
