module.exports =
	auth: require './auth'
	products: require './products'
	suppliers: require './suppliers'
	productGroups: require './product-groups'
	customers: require './customers'
	# taiga: require './taiga'
	# activity: require './activity'
	# userSettings: require './user-settings'
	# worktimeStats: require './worktime-stats'
